Switch to compose state and kotlin flows - 1. iteration
bitfireAT/icsx5 pull request #279
Opened 2024-04-10 11:37 UTC by ArnyminerZ

2024-04-10 11:54 UTC, sunkup requested changes
Please go ahead and make the functions suspendable :)

2024-04-11 08:56 UTC, sunkup commented on app/src/androidTest/java/at/bitfire/icsdroid/TestSettings.kt
> +        assert(forceDarkMode)
I believe Ricki prefers to use only junit framework assert statements. So not kotlin `assert()`, but only `assertTrue()`, `assertEquals()`, etc ...

2024-04-11 09:08 UTC, sunkup approved these changes
Nice. More tests are always good :+1: 
I just removed the `data.close()` calls. It says in the Kdoc, they don't do anything for `InputStream`.

I would like to try my hands on some of the new flow concepts as well with the 2. iteration, if that's okay with you?

2024-04-12 09:44 UTC, ArnyminerZ commented
Yup, let's merge this one and you can work on 2

2024-04-15 06:27 UTC, merged